# Generated by Django 3.2 on 2023-06-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('kibanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KibandaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kibanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kibanda.kibandaprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kibanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kibanda.kibandaprofile')),
                ('menu', models.ManyToManyField(to='administrator.Menu')),
            ],
        ),
    ]
