# Generated by Django 3.2 on 2023-06-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('kibanda', '0002_availablemenu_kibandastatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kibanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kibanda.kibandaprofile')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.menu')),
            ],
        ),
        migrations.AlterField(
            model_name='availablemenu',
            name='menu',
            field=models.ManyToManyField(to='kibanda.MenuItem'),
        ),
    ]
