# Generated by Django 3.2 on 2023-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0004_kibandaprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='ID_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kibandaprofile',
            name='aina_ya_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
