# Generated by Django 3.2 on 2023-06-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0005_auto_20230602_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='usergroup',
            field=models.CharField(default='Kibanda', max_length=50),
        ),
        migrations.CreateModel(
            name='DefaultMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kibanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kibanda.kibandaprofile')),
                ('menu', models.ManyToManyField(to='kibanda.MenuItem')),
            ],
        ),
    ]
