# Generated by Django 3.2 on 2023-06-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0006_auto_20230604_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='is_acitve',
            field=models.BooleanField(default=False),
        ),
    ]
