# Generated by Django 3.2 on 2023-06-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0007_kibandaprofile_is_acitve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kibandaprofile',
            name='is_acitve',
        ),
    ]
