# Generated by Django 3.2 on 2023-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0008_remove_kibandaprofile_is_acitve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibandastatus',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
