# Generated by Django 3.2 on 2023-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0011_kibandaprofile_profile_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
