# Generated by Django 3.2 on 2023-06-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0012_kibandaprofile_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kibanda_images'),
        ),
    ]
