# Generated by Django 3.2 on 2023-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0013_kibandaprofile_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
