# Generated by Django 3.2 on 2023-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0014_kibandaprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='is_default_meal_added',
            field=models.BooleanField(default=False),
        ),
    ]
