# Generated by Django 3.2 on 2023-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0015_kibandaprofile_is_default_meal_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
