# Generated by Django 3.2 on 2023-06-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0016_menuitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
    ]
