# Generated by Django 3.2 on 2023-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0017_remove_menuitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmenu',
            name='menu',
            field=models.ManyToManyField(blank=True, to='kibanda.MenuItem'),
        ),
    ]
