# Generated by Django 3.2 on 2023-06-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0018_alter_defaultmenu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
