# Generated by Django 3.2 on 2023-06-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0019_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmenu',
            name='kibanda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defaultmenu', to='kibanda.kibandaprofile'),
        ),
    ]
