# Generated by Django 3.2 on 2023-06-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0022_alter_availablemenu_kibanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablemenu',
            name='set_from_default_menu',
            field=models.BooleanField(default=False),
        ),
    ]
