# Generated by Django 3.2 on 2023-06-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0023_availablemenu_set_from_default_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='anadaiwa',
            field=models.BooleanField(default=False),
        ),
    ]
