# Generated by Django 3.2 on 2023-06-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0025_kibandaprofile_physical_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='cover_photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kibandaprofile',
            name='profile_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
