# Generated by Django 3.2 on 2023-06-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0026_auto_20230621_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibandaprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kibanda_images/'),
        ),
        migrations.AlterField(
            model_name='kibandaprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kibanda_images/'),
        ),
    ]
