# Generated by Django 3.2 on 2023-06-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0027_auto_20230625_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
