# Generated by Django 3.2 on 2023-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0028_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandaprofile',
            name='status',
            field=models.CharField(default='New', max_length=255),
        ),
    ]
