# Generated by Django 3.2 on 2023-07-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0029_kibandaprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibandaprofile',
            name='status',
            field=models.CharField(default='FREE', max_length=255),
        ),
    ]
