# Generated by Django 3.2 on 2024-08-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0030_alter_kibandaprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='kibanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='kibanda.kibandaprofile'),
        ),
    ]
