# Generated by Django 3.2 on 2023-06-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerprofile_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
