# Generated by Django 3.2 on 2023-06-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('kibanda', '0003_auto_20230601_1655'),
        ('main', '0003_cancelledordersbycustomer_cancelledordersbykibanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='KibandaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('rated_updated', models.DateTimeField(auto_now=True)),
                ('rating_comment', models.TextField(blank=True, null=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('rated_updated', models.DateTimeField(auto_now=True)),
                ('rating_comment', models.TextField(blank=True, null=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kibanda.kibandaprofile')),
            ],
        ),
    ]
