# Generated by Django 3.2 on 2023-06-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customerrating_kibandarating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelId', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
            ],
        ),
    ]
