# Generated by Django 3.2 on 2023-06-20 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_devicenotificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicenotificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificationToken', to=settings.AUTH_USER_MODEL),
        ),
    ]
