# Generated by Django 3.2 on 2023-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230703_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
