# Generated by Django 3.2 on 2023-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mark_as_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancelledordersbycustomer',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancelledordersbykibanda',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
