# Generated by Django 3.2 on 2023-07-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230706_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledordersbycustomer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelledorders', to='main.order'),
        ),
        migrations.AlterField(
            model_name='cancelledordersbykibanda',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejectedorders', to='main.order'),
        ),
    ]
