# Generated by Django 3.2 on 2023-07-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230706_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledordersbycustomer',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelledorder', to='main.order'),
        ),
        migrations.AlterField(
            model_name='cancelledordersbykibanda',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejectedorder', to='main.order'),
        ),
    ]
