# Generated by Django 3.2 on 2023-07-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230707_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kibanda_mark_order_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
