# Generated by Django 3.2 on 2023-07-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customerprofile_image'),
        ('main', '0019_auto_20230707_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibandarating',
            name='rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='kibandarating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
