# Generated by Django 3.2 on 2023-07-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0028_alter_menuitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_alter_kibandarating_rated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrating',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kibandarating',
            name='kibanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kibandaratings', to='kibanda.kibandaprofile'),
        ),
    ]
