# Generated by Django 3.2 on 2023-07-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kibanda', '0028_alter_menuitem_price'),
        ('main', '0022_auto_20230711_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoPaidAndHowMuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('payed_updated', models.DateTimeField(auto_now=True)),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whopaid', to='kibanda.kibandaprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('isExpired', models.BooleanField(default=False)),
                ('kibanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentrecord', to='kibanda.kibandaprofile')),
            ],
        ),
    ]
