# Generated by Django 3.2 on 2023-07-13 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kibanda', '0028_alter_menuitem_price'),
        ('main', '0023_paymentrecords_whopaidandhowmuch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReferenceNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('external_transaction_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PAID', max_length=255)),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whopaid', to=settings.AUTH_USER_MODEL)),
                ('reference_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.paymentreferencenumbers')),
            ],
        ),
        migrations.RenameModel(
            old_name='PaymentRecords',
            new_name='KibandaPayments',
        ),
        migrations.DeleteModel(
            name='WhoPaidAndHowMuch',
        ),
    ]
