# Generated by Django 3.2 on 2023-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20230713_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecords',
            name='status',
            field=models.CharField(default='NOT PAID', max_length=255),
        ),
    ]
