# Generated by Django 3.2 on 2023-07-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_transactionrecords_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibandapayments',
            name='type',
            field=models.CharField(default='FREE', max_length=255),
        ),
    ]
