# Generated by Django 3.2 on 2023-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_kibandapayments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kibandapayments',
            name='type',
            field=models.CharField(blank=True, default='FREE', max_length=255, null=True),
        ),
    ]
