# Generated by Django 3.2 on 2023-06-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotp',
            old_name='deviceID',
            new_name='phone',
        ),
    ]
