# Generated by Django 3.2 on 2023-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_deviceid_userotp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='alreadyUsed',
            field=models.BooleanField(default=False),
        ),
    ]
