# Generated by Django 3.2 on 2023-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_userotp_alreadyused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
