# Generated by Django 3.2 on 2023-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='singular_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
