# Generated by Django 3.2 on 2023-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_menu_singular_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(default='menu', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profile_images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu_images/'),
        ),
    ]
